### ISSUE TITLE
MapsAPI doesn't replace "Services Google Play"

### ISSUE THREAD

**Issue by gab12** [mar-v-in/MapsAPI#1]
Hello,

I'm on Cyanogenmod 10.1.3, and i don't installed gapps.
I installed MapsAPI v0.4 (with recovery), but it doesn't work.

When I launch an application using MapsAPI as "Runstatic", I have the message "This Maps required the services Google" with a link on the market of "services Google Play".

Is it possible to MapsAPI replace the services google play ?

Thank You

**Comment by mar-v-in** [comment]
Also I'd like to support this, it's not possible to support the newer Maps API without deep system hacks. This is because Google added some signature checking the this Play Services stuff so it should not be possible to write a drop-in replacement
