### ISSUE TITLE
Howto build inside AOSP

### ISSUE THREAD

**Issue by chr4** [mar-v-in/MapsAPI#13]
As you created an `Android.mk` file, I was wondering if it is possible to bulid this inside AOSP directly. Wouldn't it be better to not use the `com.google.android.maps` directory, but place the content directly in the repository root? Then you supposedly just add the repo into your manifest and `com.google.android.maps` in `PRODUCT_PACKAGES` and it should work?
Is there a specific reason for the directory, or am I missing something else?

**Comment by mar-v-in** [comment]
The directory is not needed, but doesn't hurt if you build using AOSP build system. The build system recurses into all subdirectories if a directory has no Android.mk in it. So adding to manifest and PRODUCT_PACKAGES (don't forget adding the XML as well) should already work.

If you don't mind having a possibly buggy version and you build from AOSP anyway I'd like to ask you to use the newer version at https://github.com/microg/android_frameworks_mapsv1 - it's no longer a modified osmdroid, but uses the latter as a library. The osmdroid version used is much more up to date for that reason.

**Comment by chr4** [comment]
Hi, thanks for your reply! I wouldn't mind trying out the new one, I'm having issues compiling it in AOSP here though, will open up an issue.
