### ISSUE TITLE
osmdroid UserAgent was banned by osm

### ISSUE THREAD

**Issue by dicer** [mar-v-in/MapsAPI#3]
Currently the MapsAPI does not load any maps:

W/MapsAPI ( 2235): MapTileDownloader: Problem downloading MapTile from 'http://tile.openstreetmap.org/0/0/0.png': /0/0/0 HTTP response: HTTP/1.1 403 Forbidden

Actually, I patched this a bit to show the URL ;) This issue seems to be fixed in a recent version of osmdroid:
https://code.google.com/p/osmdroid/issues/detail?id=515

**Comment by mar-v-in** [comment]
Thanks for reporting. Fixed in 0.5
