### ISSUE TITLE
Patchy tiles in Fake GPS Path

### ISSUE THREAD

**Issue by dalb8** [mar-v-in/MapsAPI#6]
I built https://github.com/Ryan-ZA/MockGPSPath from source with MapsAPI instead of Google APIs but the tile loading is quite patchy compared to other apps I've tried. (I got it working as an Android library alright):

```
Build:1.2.1,4
    commit=e36f56e5beca
    init=sed -i '/uses-library/d' AndroidManifest.xml && \
        sed -i 's@\(target=\).*@\1android-16@' project.properties
    rm=libs/GoogleAdMobAdsSdk-4.3.1.jar
    srclibs=1:MobAdMob@3bd78884,2:MapsAPI@323b519
```

MapsAPI:

```
Repo Type:git
Repo:https://github.com/mar-v-in/MapsAPI
Subdir:com.google.android.maps
Prepare:echo -e 'target=android-19\nandroid.library=true' >> project.properties && rm build.xml
```

**Comment by dalb8** [comment]
Another example of this is https://github.com/jpeddicord/speedofsound.git. See http://666kb.com/i/cmmnlwph4hy6fzliq.png

**Comment by mar-v-in** [comment]
Probably related to #9? Try if adding the mentioned permissions to the android manifest fixes the problem (I don't have f-droid build system running here, sorry)

**Comment by dalb8** [comment]
Adding WRITE_EXTERNAL_STORAGE seems to fix all these problems. 

One thing to watch is that some apps close each permission tag separately. but most do not e.g.. 

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"></uses-permission>
```
